server:
  port: ${server.port:0}

spring:
  profiles:
    active: dev
  application:
    name: tims-gateway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: 2004long
        file-extension: yaml
        refresh-enabled: true
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: 2004long

  config:
    import:
      - optional:nacos:${spring.application.name}-dev.yaml

